baseURL: http://igor-kuznetsov-e628.netlify.app/
languageCode: en-us
title: Portfolio website for Igor Kuznetsov
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
#      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
#      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Igor Kuznetsov
  blog: {}
  contact:
    address:
      - city: London, NW1
        street: Regents Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ikuznetsov@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (012) 345-6789 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: This  incredible website I created from the 1st attempt
  error404:
    heading: Page couldn't be found, Gosh! WHY????? 
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: John Doe Co
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      # - icon: fa-instagram
      #   label: Instagram
      #   url: https://www.instagram.com
      # - icon: fa-github
      #   label: GitHub
      #   url: https://www.github.com
      # - icon: fa-linkedin
      #   label: LinkedIn
      #   url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs/risk_return
      # - name: Generic Blog
      #   url: blogs/ipsum
      # - name: Elements
      #   url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Risk Returns
        url: blogs/risk_return
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
  #     - image: pic04.jpg
  #       subtitle: Nisl Sed Aliquam
  #       title: Ipsum
  #       url: blogs/ipsum
  #     - image: pic05.jpg
  #       subtitle: Ipsum Dolor Sit Amet
  #       title: Consequat
  #       url: blogs/ipsum
  #     - image: pic06.jpg
  #       subtitle: Feugiat Amet Tempus
  #       title: Etiam
  #       url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Igor worked for two years as a Research Professional at the Booth School of Business, University of Chicago \n
    supporting research projects in economics, accounting, and finance. \n 
    Prior to that, Igor gained substantial technical experience processing and analysing institutional data \n 
    as a research analyst at the University of British Columbia."
    title: Short Bio
    url: blogs