baseURL: http://igor-kuznetsov-e628.netlify.app/
languageCode: en-us
title:  Igor Kuznetsov
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
     Welcome to my Website.
     I am a Finace PhD Student at LBS.
    title: Igor Kuznetsov
  blog: {}
  contact:
    address:
      - city: London, NW1
        street: Regent's Park
        title: Adress
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ikuznetsov@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (012) 345-6789 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: This incredible website I created from the 1st attempt
  error404:
    heading: Page couldn't be found, Gosh! WHY????? 
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Igor Kuznetsov
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      # - icon: fa-instagram
      #   label: Instagram
      #   url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/IgorK7
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/igor-kuznetsov-8a039733/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
      - name: Analysis
        url: blogs/mass_shootings
      - name: Another Analysis
        url: blogs/risk_return
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: My Half-Life
        title: About me
        url: blogs/biography
      - image: pic02.jpg
        subtitle: Some wise words should be here
        title: Analysis
        url: blogs/mass_shootings
      - image: pic03.jpg
        subtitle: Old and Borrowed
        title: Another Analysis
        url: blogs/risk_return
  #     - image: pic04.jpg
  #       subtitle: Nisl Sed Aliquam
  #       title: Ipsum
  #       url: blogs/ipsum
  #     - image: pic05.jpg
  #       subtitle: Ipsum Dolor Sit Amet
  #       title: Consequat
  #       url: blogs/ipsum
  #     - image: pic06.jpg
  #       subtitle: Feugiat Amet Tempus
  #       title: Etiam
  #       url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Igor worked for two years as a Research Professional at the Booth School of Business, University of Chicago \n
    supporting research projects in economics, accounting, and finance. \n 
    Prior to that, Igor gained substantial technical experience processing and analysing institutional data \n 
    as a research analyst at the University of British Columbia."
    title: Short Bio
    url: blogs